### ISSUE TITLE
Failed to build on macOS (ld error).

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptIDE#1] opened 2020-08-28 17:50 UTC
@IsaacShelton 

I got the following error:

```
ld: unexpected token: !tapi-tbd-v3 file '/System/Library/Frameworks//Cocoa.framework/Cocoa.tbd' for architecture x86_64
```

Compilation succeed but link failed.

**Comment by IsaacShelton** [comment] 2020-08-28 19:31
It looks like a problem with your toolchain...

`-framework Cocoa` seems to be the cause, but it's a required dependency for GLFW

From what I've seen online, this might be fixed by updating your XCode toolchain.

*"The correct solution would be to update the ld64-latest port to a newer version. But that appears to be difficult. See: https://trac.macports.org/ticket/53784"*

If you don't care to compile it yourself, I've published a snapshot build for MacOS

EDIT: The installer/standalone are now working correctly

**Comment by ghost** [comment] 2020-08-29 09:01
@IsaacShelton 

It works! I updated my Xcode up to 11. Everything works, but the `AdeptIDE.app` does not opens. I can run GUI only through binary file.

**Comment by IsaacShelton** [comment] 2020-08-29 16:04
Glad to hear! The reason the AdeptIDE.app file doesn't work is because it's actually just a stub .app which wraps a shell script which launches the actual binary. You can either edit the script inside it under <show package contents>/Contents/MacOS, or you can remove the script and then copy the binary, assets folder, settings.json, and optionally the playground folder into its place and it should then work as a standalone .app file which you can move to /Applications or ~/Applications.

If you need any tips regarding the control scheme, since it is quite weird, there are a bunch of key shortcuts listed on the releases page. Good luck!

**Closed as completed by IsaacShelton** 2020-08-29 16:04 UTC
Labels: build-related
